import swaggerJsdoc from "swagger-jsdoc";

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Pawsomeday Backend API",
      version: "1.0.0",
      description: "API documentation generated by Swagger",
    },
    servers: [
      {
        url: "http://localhost:8080",
      },
      {
        url: "http://54.241.94.183:8080",
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
  },
  apis: ["./src/routes/*.ts"],
};

const swaggerSpecs = swaggerJsdoc(options);
export default swaggerSpecs;
