name: Deploy to Ubuntu EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SERVER_USER: ubuntu
      SERVER_IP: ${{ secrets.SERVER_IP }}
      ENV_FILE: ${{ secrets.ENV_FILE }}
      FIREBASE_ADMIN_SDK_KEY: ${{secrets.FIREBASE_ADMIN_SDK_KEY}}
      FIREBASE_ADMIN_SDK_KEY_FILE_NAME: ${{secrets.FIREBASE_ADMIN_SDK_KEY_FILE_NAME}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      # .env 파일을 CI 서버에 생성
      - name: Create .env file on CI server
        run: echo "${ENV_FILE}" > .env

      # Firebase Admin SDK Key 파일 생성
      - name: Create Firebase Admin SDK Key File
        run: echo "${FIREBASE_ADMIN_SDK_KEY}" > "${FIREBASE_ADMIN_SDK_KEY_FILE_NAME}"

      # Prisma 마이그레이션 적용
      - name: Apply Prisma migrations
        run: npx prisma migrate deploy

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build TypeScript
        run: npm run build

      # 컴파일된 파일과 .env 파일을 원격 서버로 전송
      - name: Deploy to Ubuntu EC2
        run: |
          echo "${SSH_KEY}" > ssh_key.pem
          chmod 600 ssh_key.pem

          # 원격 서버로 dist 폴더와 .env 파일 복사
          scp -o StrictHostKeyChecking=no -i ssh_key.pem -r dist ${SERVER_USER}@${SERVER_IP}:/home/ubuntu/back
          scp -o StrictHostKeyChecking=no -i ssh_key.pem .env ${SERVER_USER}@${SERVER_IP}:/home/ubuntu/back/.env

          # SSH를 통해 원격 서버에서 PM2로 애플리케이션 실행
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${SERVER_USER}@${SERVER_IP} << 'EOF'
            cd /home/ubuntu/back
            git pull origin develop
            npm install --production
            pm2 delete pawsomeday || true
            pm2 start dist/app.js --name "pawsomeday"
          EOF
